trigger:
- feature

pool:
  #vmImage: windows-2019
  name: vardhantestgl

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      curl \
        -X DELETE \
        -H "Accept: application/vnd.github+json" \ 
        -H "Authorization: Bearer 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" \
        https://api.github.com/repos/pamulavardhan/azure-vm-offer-hello-world-20201/branches/feature/protection